### ISSUE TITLE
windows系统中使用npm run build 命令报错

### ISSUE THREAD

**Issue by 76wenshu** [76wenshu/ECMA-262ChineseDoc#4]
报错情况：
Terminal show:

> ecma262@1.0.0 build
> npm run build-head

> ecma262@1.0.0 build-head
> npm run build-only -- --lint-spec --strict

> ecma262@1.0.0 prebuild-only
> npm run clean && mkdir out && cp -R img out

> ecma262@1.0.0 clean
> rm -rf out

'rm' 不是内部或外部命令，也不是可运行的程序

**Comment by 76wenshu** [comment]
解决措施：
错误原因可能：使用了Linux 下的 rm -rf 命令，你的电脑是windows
解决办法：把rm -rf 命令替换为 rimraf 命令（文件中的rm -rf）改一下试试

windows 运行命令行记得是用 Git Bash Here 运行

npm install rimraf --save-dev

npm install

npm run build

Node.js 13.14.0 npm 6.14.4 版本以上应该都可以

**Comment by denghauran** [comment]
### 补充以下情况

**如果要在windows正常运行，需要做以下事情：**

- 将`package.json`中的`"clean": "rm -rf out"`和`"prebuild-only": "npm run clean && mkdir out && cp -R img out"`改为`"clean": "rimraf out"`和`"prebuild-only": "npm run clean && mkdir out && xcopy img /s out "`
- 在vscode中将`spec.html`、`table-binary-unicode-properties.html`和`table-nonbinary-unicode-properties.html`的换行改为LF

**原因：**

- 原本开发过程中使用的系统非Windows，命令行命令无法被window识别，改成cmd就行了
- 当与很多人一起开发时，他们都拥有不同的编辑器、VCS 应用程序和操作系统，可能会出现由上述任何一个编写的不同行尾，Windows 操作系统中使用的换行符（新行）通常是回车符（CR）后跟换行符（LF），使其成为回车换行符（CRLF），而 Linux 和 Unix 使用简单的换行符（LF）。对应的控制序列是"\n"（对于LF）和"\r\n"对于（CRLF）。
