### ISSUE TITLE
Translation LN 54-91

### ISSUE THREAD

**Issue by 76wenshu** [76wenshu/ECMA-262ChineseDoc#5]
spec.html

LN 54-91(代码行数)

person : 76wenshu

**Comment by denghauran** [comment]
翻译好的文档是什么格式，放在仓库的哪个文件夹下？关于这个行数是什么看的，我这没有显示什么行数？

**Comment by 76wenshu** [comment]
ecma262ChineseDoc  --> spec.html 你好这spec.html个文件的代码函数函数就可以的。
